# Generated by Django 5.1.2 on 2024-10-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='景点名称')),
                ('distance', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='距离(公里)')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='评分')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(upload_to='attractions/', verbose_name='景点图片')),
            ],
            options={
                'verbose_name': '周边景点',
                'verbose_name_plural': '周边景点',
                'ordering': ['distance'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='设施名称')),
                ('category', models.CharField(choices=[('basic', '基础设施'), ('bathroom', '浴室设施'), ('media', '媒体设施'), ('other', '其他设施')], max_length=50, verbose_name='设施类别')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标类名')),
            ],
            options={
                'verbose_name': '设施',
                'verbose_name_plural': '设施',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房间名称')),
                ('bed_type', models.CharField(max_length=100, verbose_name='床型')),
                ('area', models.CharField(max_length=50, verbose_name='面积')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('window', models.BooleanField(verbose_name='是否有窗')),
                ('max_guests', models.IntegerField(verbose_name='最大入住人数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('smoking', models.BooleanField(default=True, verbose_name='是否可吸烟')),
                ('image', models.ImageField(blank=True, upload_to='rooms/', verbose_name='房间图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('facilities', models.ManyToManyField(related_name='rooms', to='main.facility', verbose_name='设施')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='入住日期')),
                ('check_out', models.DateField(verbose_name='退房日期')),
                ('guest_name', models.CharField(max_length=100, verbose_name='客人姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='房间')),
            ],
            options={
                'verbose_name': '预订',
                'verbose_name_plural': '预订',
                'ordering': ['-created_at'],
            },
        ),
    ]
