# Generated by Django 5.1.2 on 2024-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': '预订', 'verbose_name_plural': '预订'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='特殊要求'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='总价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(verbose_name='离店日期'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(max_length=50, verbose_name='床型'),
        ),
        migrations.AlterField(
            model_name='room',
            name='smoking',
            field=models.BooleanField(default=False, verbose_name='是否可吸烟'),
        ),
        migrations.AlterField(
            model_name='room',
            name='window',
            field=models.BooleanField(default=True, verbose_name='是否有窗'),
        ),
    ]
